"""
Alert Service for PRISM.
Handles alert rules, threshold checking, email notifications, and alert history.
"""

import os
import uuid
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


# ── Email helper ──────────────────────────────────────────────────────────────

def _send_email(to: str, subject: str, body_html: str) -> bool:
    """Send an email via SMTP. Returns True on success."""
    if os.getenv("EMAIL_ENABLED", "false").lower() != "true":
        logger.info(f"[PRISM Alerts] Email disabled — would have sent to {to}: {subject}")
        return False

    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USERNAME", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    smtp_from = os.getenv("SMTP_FROM", smtp_user)

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_from
        msg["To"] = to
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_from, [to], msg.as_string())

        logger.info(f"[PRISM Alerts] Email sent to {to}: {subject}")
        return True

    except Exception as e:
        logger.error(f"[PRISM Alerts] Email failed: {e}")
        return False


def _alert_email_html(alert: dict, current_value: float) -> str:
    """Generate a nice HTML email body for an alert trigger."""
    color = "#e53e3e" if alert["severity"] == "critical" else "#dd6b20"
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;border:1px solid #e2e8f0;border-radius:8px;">
        <div style="background:{color};color:white;padding:16px;border-radius:6px;margin-bottom:20px;">
            <h2 style="margin:0;">⚠️ PRISM Alert Triggered</h2>
        </div>
        <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Alert Name</td>
                <td style="padding:8px;">{alert['name']}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Metric</td>
                <td style="padding:8px;">{alert['metric']}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Condition</td>
                <td style="padding:8px;">{alert['condition']} {alert['threshold']}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Current Value</td>
                <td style="padding:8px;color:{color};font-weight:bold;">{current_value}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Severity</td>
                <td style="padding:8px;">{alert['severity'].upper()}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Triggered At</td>
                <td style="padding:8px;">{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC</td></tr>
        </table>
        <p style="margin-top:20px;color:#718096;font-size:12px;">
            This alert was generated by PRISM — AI Desktop Copilot
        </p>
    </div>
    """


# ── AlertService ──────────────────────────────────────────────────────────────

class AlertService:
    """
    Manages alert rules, evaluates thresholds, sends notifications,
    and maintains alert history.
    """

    def __init__(self):
        # alert_id → alert dict
        self._alerts: Dict[str, Dict[str, Any]] = {}
        # list of triggered alert events
        self._history: List[Dict[str, Any]] = []

    # ── CRUD ──────────────────────────────────────────────────────────────────

    def create_alert(
        self,
        name: str,
        metric: str,
        condition: str,          # "gt", "lt", "gte", "lte", "eq"
        threshold: float,
        connection_id: str,
        sql_query: str,
        recipients: List[str],
        severity: str = "warning",   # "warning" or "critical"
        description: str = "",
    ) -> Dict[str, Any]:
        """Create a new alert rule."""

        if condition not in ("gt", "lt", "gte", "lte", "eq"):
            raise ValueError(f"Invalid condition '{condition}'. Use: gt, lt, gte, lte, eq")
        if severity not in ("warning", "critical"):
            raise ValueError("Severity must be 'warning' or 'critical'")
        if not sql_query.strip().lower().startswith("select"):
            raise ValueError("Alert SQL must be a SELECT query")

        alert_id = str(uuid.uuid4())
        alert = {
            "id": alert_id,
            "name": name,
            "description": description,
            "metric": metric,
            "condition": condition,
            "threshold": threshold,
            "connection_id": connection_id,
            "sql_query": sql_query.strip(),
            "recipients": recipients,
            "severity": severity,
            "is_active": True,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "last_checked": None,
            "last_triggered": None,
            "trigger_count": 0,
        }
        self._alerts[alert_id] = alert
        logger.info(f"[PRISM Alerts] Created alert '{name}' ({alert_id})")
        return alert

    def get_alert(self, alert_id: str) -> Optional[Dict[str, Any]]:
        return self._alerts.get(alert_id)

    def list_alerts(self, user_id: str = None) -> List[Dict[str, Any]]:
        return list(self._alerts.values())

    def update_alert(self, alert_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        alert = self._alerts.get(alert_id)
        if not alert:
            return None
        allowed = {"name", "description", "threshold", "condition", "recipients", "severity", "sql_query"}
        for key, value in updates.items():
            if key in allowed:
                alert[key] = value
        logger.info(f"[PRISM Alerts] Updated alert {alert_id}")
        return alert

    def delete_alert(self, alert_id: str) -> bool:
        if alert_id in self._alerts:
            del self._alerts[alert_id]
            logger.info(f"[PRISM Alerts] Deleted alert {alert_id}")
            return True
        return False

    def pause_alert(self, alert_id: str) -> bool:
        alert = self._alerts.get(alert_id)
        if alert:
            alert["is_active"] = False
            return True
        return False

    def resume_alert(self, alert_id: str) -> bool:
        alert = self._alerts.get(alert_id)
        if alert:
            alert["is_active"] = True
            return True
        return False

    # ── Evaluation ────────────────────────────────────────────────────────────

    def _evaluate_condition(self, value: float, condition: str, threshold: float) -> bool:
        if condition == "gt":  return value > threshold
        if condition == "lt":  return value < threshold
        if condition == "gte": return value >= threshold
        if condition == "lte": return value <= threshold
        if condition == "eq":  return value == threshold
        return False

    async def check_alert(self, alert_id: str) -> Dict[str, Any]:
        """
        Run the alert's SQL query, evaluate the threshold, and
        send email notification if triggered.
        """
        from .database_manager import db_manager

        alert = self._alerts.get(alert_id)
        if not alert:
            return {"success": False, "error": "Alert not found"}
        if not alert["is_active"]:
            return {"success": True, "triggered": False, "reason": "Alert is paused"}

        try:
            success, columns, results, error = await db_manager.execute_query(
                connection_id=alert["connection_id"],
                sql=alert["sql_query"],
            )

            alert["last_checked"] = datetime.now(timezone.utc).isoformat()

            if not success:
                return {"success": False, "error": error}

            # Extract numeric value from first cell of first row
            if not results or not columns:
                return {"success": False, "error": "Query returned no results"}

            raw_value = results[0].get(columns[0], 0)
            current_value = float(raw_value) if raw_value is not None else 0.0

            triggered = self._evaluate_condition(
                current_value, alert["condition"], alert["threshold"]
            )

            result = {
                "success": True,
                "alert_id": alert_id,
                "alert_name": alert["name"],
                "current_value": current_value,
                "threshold": alert["threshold"],
                "condition": alert["condition"],
                "triggered": triggered,
                "checked_at": alert["last_checked"],
            }

            if triggered:
                alert["last_triggered"] = alert["last_checked"]
                alert["trigger_count"] += 1

                # Log to history
                history_entry = {
                    "id": str(uuid.uuid4()),
                    "alert_id": alert_id,
                    "alert_name": alert["name"],
                    "current_value": current_value,
                    "threshold": alert["threshold"],
                    "condition": alert["condition"],
                    "severity": alert["severity"],
                    "triggered_at": alert["last_triggered"],
                }
                self._history.append(history_entry)
                # Keep only last 500 history entries
                if len(self._history) > 500:
                    self._history = self._history[-500:]

                # Send email to all recipients
                subject = f"🚨 PRISM Alert: {alert['name']} — {alert['severity'].upper()}"
                body = _alert_email_html(alert, current_value)
                for recipient in alert["recipients"]:
                    _send_email(recipient, subject, body)

                result["email_sent"] = True

            return result

        except Exception as e:
            logger.error(f"[PRISM Alerts] check_alert error: {e}")
            return {"success": False, "error": str(e)}

    async def check_all_alerts(self) -> List[Dict[str, Any]]:
        """Check all active alerts — called by APScheduler."""
        results = []
        for alert_id in list(self._alerts.keys()):
            result = await check_alert(alert_id)
            results.append(result)
        return results

    # ── History ───────────────────────────────────────────────────────────────

    def get_history(self, alert_id: str = None, limit: int = 100) -> List[Dict[str, Any]]:
        """Get alert trigger history, optionally filtered by alert_id."""
        history = self._history
        if alert_id:
            history = [h for h in history if h["alert_id"] == alert_id]
        return list(reversed(history))[:limit]

    def clear_history(self, alert_id: str = None) -> int:
        """Clear history. Returns number of entries removed."""
        if alert_id:
            before = len(self._history)
            self._history = [h for h in self._history if h["alert_id"] != alert_id]
            return before - len(self._history)
        else:
            count = len(self._history)
            self._history = []
            return count


# Singleton
alert_service = AlertService()