"""
Alert Service for PRISM.
Handles alert rules, threshold checking, email notifications, and alert history.
"""

import os
import uuid
import json
import smtplib
import logging
import httpx
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


# ── Email helper ──────────────────────────────────────────────────────────────

def _send_email(to: str, subject: str, body_html: str) -> bool:
    """Send an email via SMTP. Returns True on success."""
    if os.getenv("EMAIL_ENABLED", "false").lower() != "true":
        logger.info(f"[PRISM Alerts] Email disabled — would have sent to {to}: {subject}")
        return False

    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USERNAME", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    smtp_from = os.getenv("SMTP_FROM", smtp_user)

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_from
        msg["To"] = to
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_from, [to], msg.as_string())

        logger.info(f"[PRISM Alerts] Email sent to {to}: {subject}")
        return True

    except Exception as e:
        logger.error(f"[PRISM Alerts] Email failed: {e}")
        return False


def _alert_email_html(alert: dict, current_value: float) -> str:
    """Generate a nice HTML email body for an alert trigger."""
    color = "#e53e3e" if alert["severity"] == "critical" else "#dd6b20"
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;border:1px solid #e2e8f0;border-radius:8px;">
        <div style="background:{color};color:white;padding:16px;border-radius:6px;margin-bottom:20px;">
            <h2 style="margin:0;">⚠️ PRISM Alert Triggered</h2>
        </div>
        <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Alert Name</td>
                <td style="padding:8px;">{alert['name']}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Metric</td>
                <td style="padding:8px;">{alert['metric']}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Condition</td>
                <td style="padding:8px;">{alert['condition']} {alert['threshold']}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Current Value</td>
                <td style="padding:8px;color:{color};font-weight:bold;">{current_value}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Severity</td>
                <td style="padding:8px;">{alert['severity'].upper()}</td></tr>
            <tr style="background:#f7fafc;"><td style="padding:8px;font-weight:bold;color:#4a5568;">Triggered At</td>
                <td style="padding:8px;">{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC</td></tr>
        </table>
        <p style="margin-top:20px;color:#718096;font-size:12px;">
            This alert was generated by PRISM — AI Desktop Copilot
        </p>
    </div>
    """


# ── NL → SQL helpers ─────────────────────────────────────────────────────────
# Reuses the same AI provider env vars as the /suggestions endpoint
# (AI_API_KEY, AI_BASE_URL, AI_MODEL) so no new config is required.

def _looks_like_sql(text: str) -> bool:
    """Heuristic: does this already look like a SQL SELECT/CTE query?"""
    return text.strip().lower().startswith(("select", "with"))


def _build_schema_context(schema_data: dict) -> str:
    """Turn discover_full_schema() output into a compact prompt-friendly string."""
    lines = []
    for table in schema_data.get("tables", []):
        cols = [c.get("name", "") for c in table.get("columns", [])]
        lines.append(f"{table.get('name', '')}({', '.join(cols)})")
    return "\n".join(lines) if lines else "(no tables found)"


def _clean_sql_response(text: str) -> str:
    """Strip markdown code fences / language tags / trailing semicolons from an AI SQL response."""
    text = (text or "").strip()

    if text.startswith("```"):
        parts = text.split("```")
        # parts: ['', 'sql\nSELECT ...', ''] typically
        text = parts[1] if len(parts) > 1 else text.strip("`")
        stripped = text.lstrip()
        if stripped[:4].lower().startswith("sql\n") or stripped[:3].lower() == "sql":
            # remove leading "sql" language tag
            text = stripped[3:].lstrip("\n").strip()
        else:
            text = stripped.strip()

    text = text.strip().rstrip(";").strip()
    return text


async def _call_ai_for_sql(natural_language: str, schema_context: str) -> str:
    """Call the configured AI provider (Groq-compatible) to convert plain English into SQL."""
    api_key = os.getenv("AI_API_KEY")
    base_url = os.getenv("AI_BASE_URL")
    model = os.getenv("AI_MODEL")

    prompt = f"""You are a SQL generator for a PostgreSQL database. Convert the natural language request below into a single valid SQL SELECT query.

Database schema (table(columns)):
{schema_context}

Rules:
- Output ONLY the raw SQL query. No explanation, no markdown code fences, no comments.
- The query MUST start with SELECT (or WITH ... SELECT).
- Only use tables and columns that appear in the schema above.
- For counts, use COUNT(*).
- For "today", use CURRENT_DATE for date comparisons; for timestamp columns use date_trunc('day', column) = CURRENT_DATE.
- Return a single scalar-friendly result where possible (e.g. one aggregate column) unless the request clearly asks for multiple rows/columns.

Natural language request: "{natural_language}"

SQL query:"""

    async with httpx.AsyncClient() as client:
        res = await client.post(
            f"{base_url}/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 300,
                "temperature": 0,
            },
            timeout=20.0,
        )
        res.raise_for_status()
        data = res.json()
        return data["choices"][0]["message"]["content"].strip()


# ── AlertService ──────────────────────────────────────────────────────────────

class AlertService:
    """
    Manages alert rules, evaluates thresholds, sends notifications,
    and maintains alert history.
    """

    def __init__(self):
        # alert_id → alert dict
        self._alerts: Dict[str, Dict[str, Any]] = {}
        # list of triggered alert events
        self._history: List[Dict[str, Any]] = []
        # APScheduler instance (started via start_scheduler())
        self._scheduler = None

    # ── Scheduler (NEW) ──────────────────────────────────────────────────────
    # Follows the same pattern as ReportGenerator.start_scheduler()/stop_scheduler().
    # Rather than one cron job per alert, a single 1-minute "heartbeat" job checks
    # every active alert and runs check_alert() only if its own check_interval_minutes
    # has elapsed since it was last checked. This makes create/pause/delete/update
    # take effect immediately without touching the scheduler.

    def start_scheduler(self):
        """Start APScheduler for automated alert checking."""
        try:
            from apscheduler.schedulers.asyncio import AsyncIOScheduler
            self._scheduler = AsyncIOScheduler()
            self._scheduler.add_job(
                self._run_scheduled_checks,
                trigger="interval",
                minutes=1,
                id="alert_heartbeat",
                replace_existing=True,
            )
            self._scheduler.start()
            logger.info("[PRISM Alerts] Scheduler started (heartbeat every 1 minute)")
        except ImportError:
            logger.warning("[PRISM Alerts] APScheduler not installed — automatic alert checking disabled")

    def stop_scheduler(self):
        if self._scheduler and self._scheduler.running:
            self._scheduler.shutdown()
            logger.info("[PRISM Alerts] Scheduler stopped")

    def _minutes_since(self, iso_str: Optional[str]) -> float:
        """Minutes elapsed since an ISO timestamp. Returns +inf if missing/unparseable."""
        if not iso_str:
            return float("inf")
        try:
            dt = datetime.fromisoformat(iso_str)
        except Exception:
            return float("inf")
        return (datetime.now(timezone.utc) - dt).total_seconds() / 60.0

    async def _run_scheduled_checks(self):
        """Called every minute by the scheduler; checks any alert that's due."""
        for alert_id, alert in list(self._alerts.items()):
            if not alert.get("is_active"):
                continue

            interval = alert.get("check_interval_minutes") or 5
            reference_ts = alert.get("last_checked") or alert.get("created_at")
            elapsed = self._minutes_since(reference_ts)

            if elapsed >= interval:
                logger.info(
                    f"[PRISM Alerts] Auto-checking '{alert['name']}' "
                    f"(interval={interval}m, elapsed={elapsed:.1f}m)"
                )
                try:
                    await self.check_alert(alert_id)
                except Exception as e:
                    logger.error(f"[PRISM Alerts] Scheduled check failed for {alert_id}: {e}")

    # ── NL → SQL ─────────────────────────────────────────────────────────────

    async def _get_schema_context(self, connection_id: str) -> str:
        """Fetch and format the schema for a connection, for use in AI prompts."""
        from .schema_discovery import schema_discovery

        schema_data = await schema_discovery.discover_full_schema(connection_id)
        return _build_schema_context(schema_data)

    async def convert_natural_language_to_sql(self, natural_language: str, connection_id: str) -> str:
        """
        Convert a plain-English monitoring request (e.g. "count total leads today")
        into a validated SQL SELECT query, using the connection's live schema as context.
        Raises ValueError with a user-friendly message on failure.
        """
        try:
            schema_context = await self._get_schema_context(connection_id)
        except Exception as e:
            logger.error(f"[PRISM Alerts] Schema lookup failed during NL→SQL: {e}")
            raise ValueError(
                "Could not read the database schema to understand your query. "
                "Make sure the connection is active, or enter SQL directly."
            )

        try:
            raw_response = await _call_ai_for_sql(natural_language, schema_context)
        except Exception as e:
            logger.error(f"[PRISM Alerts] AI call failed during NL→SQL: {e}")
            raise ValueError(
                "Failed to convert your query into SQL right now. "
                "Please try rephrasing, or enter SQL directly."
            )

        sql = _clean_sql_response(raw_response)

        if not _looks_like_sql(sql):
            raise ValueError(
                "Couldn't turn that into a valid SQL SELECT query. "
                "Try rephrasing (e.g. 'count of leads today') or enter SQL directly."
            )

        return sql

    # ── CRUD ──────────────────────────────────────────────────────────────────

    async def create_alert(
        self,
        name: str,
        metric: str,
        condition: str,          # "gt", "lt", "gte", "lte", "eq"
        threshold: float,
        connection_id: str,
        sql_query: str,
        recipients: List[str],
        severity: str = "warning",   # "warning" or "critical"
        description: str = "",
        check_interval_minutes: int = 5,   # NEW: how often the scheduler auto-checks this alert
    ) -> Dict[str, Any]:
        """Create a new alert rule.

        `sql_query` may be either raw SQL (starting with SELECT/WITH) or a
        plain-English description of what to monitor (e.g. "count total leads
        today") — plain English is automatically converted to SQL using the
        connection's schema before validation.

        `check_interval_minutes` controls how often the background scheduler
        (see start_scheduler()) automatically re-checks this alert without
        anyone clicking "Check Now".
        """

        if condition not in ("gt", "lt", "gte", "lte", "eq"):
            raise ValueError(f"Invalid condition '{condition}'. Use: gt, lt, gte, lte, eq")
        if severity not in ("warning", "critical"):
            raise ValueError("Severity must be 'warning' or 'critical'")
        if not check_interval_minutes or check_interval_minutes < 1:
            check_interval_minutes = 5

        original_input: Optional[str] = None
        if not _looks_like_sql(sql_query):
            original_input = sql_query.strip()
            sql_query = await self.convert_natural_language_to_sql(original_input, connection_id)
            logger.info(f"[PRISM Alerts] Converted NL '{original_input}' → SQL: {sql_query}")

        if not sql_query.strip().lower().startswith("select"):
            raise ValueError("Alert SQL must be a SELECT query")

        alert_id = str(uuid.uuid4())
        alert = {
            "id": alert_id,
            "name": name,
            "description": description,
            "metric": metric,
            "condition": condition,
            "threshold": threshold,
            "connection_id": connection_id,
            "sql_query": sql_query.strip(),
            "original_input": original_input,           # the plain-English text, if any
            "recipients": recipients,
            "severity": severity,
            "check_interval_minutes": check_interval_minutes,  # NEW
            "is_active": True,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "last_checked": None,
            "last_triggered": None,
            "trigger_count": 0,
        }
        self._alerts[alert_id] = alert
        logger.info(
            f"[PRISM Alerts] Created alert '{name}' ({alert_id}) — "
            f"auto-checks every {check_interval_minutes}m"
        )
        return alert

    def get_alert(self, alert_id: str) -> Optional[Dict[str, Any]]:
        return self._alerts.get(alert_id)

    def list_alerts(self, user_id: str = None) -> List[Dict[str, Any]]:
        return list(self._alerts.values())

    def update_alert(self, alert_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        alert = self._alerts.get(alert_id)
        if not alert:
            return None
        allowed = {
            "name", "description", "threshold", "condition", "recipients",
            "severity", "sql_query", "check_interval_minutes",  # NEW
        }
        for key, value in updates.items():
            if key in allowed:
                alert[key] = value
        logger.info(f"[PRISM Alerts] Updated alert {alert_id}")
        return alert

    def delete_alert(self, alert_id: str) -> bool:
        if alert_id in self._alerts:
            del self._alerts[alert_id]
            logger.info(f"[PRISM Alerts] Deleted alert {alert_id}")
            return True
        return False

    def pause_alert(self, alert_id: str) -> bool:
        alert = self._alerts.get(alert_id)
        if alert:
            alert["is_active"] = False
            return True
        return False

    def resume_alert(self, alert_id: str) -> bool:
        alert = self._alerts.get(alert_id)
        if alert:
            alert["is_active"] = True
            return True
        return False

    # ── Evaluation ────────────────────────────────────────────────────────────

    def _evaluate_condition(self, value: float, condition: str, threshold: float) -> bool:
        if condition == "gt":  return value > threshold
        if condition == "lt":  return value < threshold
        if condition == "gte": return value >= threshold
        if condition == "lte": return value <= threshold
        if condition == "eq":  return value == threshold
        return False

    async def check_alert(self, alert_id: str) -> Dict[str, Any]:
        """
        Run the alert's SQL query, evaluate the threshold, and
        send email notification if triggered.
        """
        from .database_manager import db_manager

        alert = self._alerts.get(alert_id)
        if not alert:
            return {"success": False, "error": "Alert not found"}
        if not alert["is_active"]:
            return {"success": True, "triggered": False, "reason": "Alert is paused"}

        try:
            success, columns, results, error = await db_manager.execute_query(
                connection_id=alert["connection_id"],
                sql=alert["sql_query"],
            )

            alert["last_checked"] = datetime.now(timezone.utc).isoformat()

            if not success:
                return {"success": False, "error": error}

            # Extract numeric value from first cell of first row
            if not results or not columns:
                return {"success": False, "error": "Query returned no results"}

            raw_value = results[0].get(columns[0], 0)
            current_value = float(raw_value) if raw_value is not None else 0.0

            triggered = self._evaluate_condition(
                current_value, alert["condition"], alert["threshold"]
            )

            result = {
                "success": True,
                "alert_id": alert_id,
                "alert_name": alert["name"],
                "current_value": current_value,
                "threshold": alert["threshold"],
                "condition": alert["condition"],
                "triggered": triggered,
                "checked_at": alert["last_checked"],
            }

            if triggered:
                alert["last_triggered"] = alert["last_checked"]
                alert["trigger_count"] += 1

                # Log to history
                history_entry = {
                    "id": str(uuid.uuid4()),
                    "alert_id": alert_id,
                    "alert_name": alert["name"],
                    "current_value": current_value,
                    "threshold": alert["threshold"],
                    "condition": alert["condition"],
                    "severity": alert["severity"],
                    "triggered_at": alert["last_triggered"],
                }
                self._history.append(history_entry)
                # Keep only last 500 history entries
                if len(self._history) > 500:
                    self._history = self._history[-500:]

                # Send email to all recipients
                subject = f"🚨 PRISM Alert: {alert['name']} — {alert['severity'].upper()}"
                body = _alert_email_html(alert, current_value)
                for recipient in alert["recipients"]:
                    _send_email(recipient, subject, body)

                result["email_sent"] = True

            return result

        except Exception as e:
            logger.error(f"[PRISM Alerts] check_alert error: {e}")
            return {"success": False, "error": str(e)}

    async def check_all_alerts(self) -> List[Dict[str, Any]]:
        """Check all active alerts on demand (e.g. from an admin endpoint)."""
        results = []
        for alert_id in list(self._alerts.keys()):
            result = await self.check_alert(alert_id)
            results.append(result)
        return results

    # ── History ───────────────────────────────────────────────────────────────

    def get_history(self, alert_id: str = None, limit: int = 100) -> List[Dict[str, Any]]:
        """Get alert trigger history, optionally filtered by alert_id."""
        history = self._history
        if alert_id:
            history = [h for h in history if h["alert_id"] == alert_id]
        return list(reversed(history))[:limit]

    def clear_history(self, alert_id: str = None) -> int:
        """Clear history. Returns number of entries removed."""
        if alert_id:
            before = len(self._history)
            self._history = [h for h in self._history if h["alert_id"] != alert_id]
            return before - len(self._history)
        else:
            count = len(self._history)
            self._history = []
            return count


# Singleton
alert_service = AlertService()