"""
Report generation service for PRISM.
Generates scheduled reports from SQL queries and delivers via email.
"""

import os
import uuid
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone

from ..models.database import QueryResponse, ExportFormat, ExportRequest, DatabaseDialect
from ..config import get_settings
from .export_service import export_service
from .database_manager import db_manager

logger = logging.getLogger(__name__)


# ── Email with attachment ─────────────────────────────────────────────────────

def _send_report_email(to_list: List[str], subject: str, body_html: str, filepath: str) -> bool:
    """Send report email with file attachment."""
    if os.getenv("EMAIL_ENABLED", "false").lower() != "true":
        logger.info(f"[PRISM Reports] Email disabled — would have sent report to {to_list}")
        return False

    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USERNAME", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    smtp_from = os.getenv("SMTP_FROM", smtp_user)

    try:
        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = smtp_from
        msg["To"] = ", ".join(to_list)
        msg.attach(MIMEText(body_html, "html"))

        # Attach the report file
        if filepath and os.path.exists(filepath):
            filename = os.path.basename(filepath)
            with open(filepath, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename={filename}")
            msg.attach(part)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_from, to_list, msg.as_string())

        logger.info(f"[PRISM Reports] Report emailed to {to_list}")
        return True

    except Exception as e:
        logger.error(f"[PRISM Reports] Email failed: {e}")
        return False


def _report_email_html(template: dict, row_count: int, filepath: str) -> str:
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;
                border:1px solid #e2e8f0;border-radius:8px;">
        <div style="background:#4472C4;color:white;padding:16px;border-radius:6px;margin-bottom:20px;">
            <h2 style="margin:0;">📊 PRISM Scheduled Report</h2>
        </div>
        <p>Your scheduled report is ready.</p>
        <table style="width:100%;border-collapse:collapse;">
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Report Name</td>
                <td style="padding:8px;">{template['name']}</td></tr>
            <tr style="background:#f7fafc;">
                <td style="padding:8px;font-weight:bold;color:#4a5568;">Description</td>
                <td style="padding:8px;">{template.get('description','')}</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Rows</td>
                <td style="padding:8px;">{row_count}</td></tr>
            <tr style="background:#f7fafc;">
                <td style="padding:8px;font-weight:bold;color:#4a5568;">Generated At</td>
                <td style="padding:8px;">{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC</td></tr>
            <tr><td style="padding:8px;font-weight:bold;color:#4a5568;">Schedule</td>
                <td style="padding:8px;">{template.get('schedule','manual')}</td></tr>
        </table>
        <p style="margin-top:16px;">The report file is attached to this email.</p>
        <p style="margin-top:20px;color:#718096;font-size:12px;">
            Generated by PRISM — AI Desktop Copilot
        </p>
    </div>
    """


# ── ReportGenerator ───────────────────────────────────────────────────────────

class ReportGenerator:
    """
    Automated report generation service.
    Generates scheduled reports from SQL queries and emails them.
    """

    def __init__(self):
        self.settings = get_settings()
        self._report_templates: Dict[str, Dict[str, Any]] = {}
        self._scheduler = None

    # ── Scheduler ─────────────────────────────────────────────────────────────

    def start_scheduler(self):
        """Start APScheduler for automated report delivery."""
        try:
            from apscheduler.schedulers.asyncio import AsyncIOScheduler
            self._scheduler = AsyncIOScheduler()
            self._scheduler.start()
            logger.info("[PRISM Reports] Scheduler started")
            # Re-register any existing scheduled templates
            for template in self._report_templates.values():
                if template.get("schedule"):
                    self._schedule_template(template)
        except ImportError:
            logger.warning("[PRISM Reports] APScheduler not installed — scheduling disabled")

    def stop_scheduler(self):
        if self._scheduler and self._scheduler.running:
            self._scheduler.shutdown()
            logger.info("[PRISM Reports] Scheduler stopped")

    def _schedule_template(self, template: dict):
        """Add a cron job for a template based on its schedule string."""
        if not self._scheduler:
            return

        schedule = template.get("schedule", "")
        template_id = template["id"]

        # Remove existing job if any
        try:
            self._scheduler.remove_job(f"report_{template_id}")
        except Exception:
            pass

        # Parse schedule: "daily", "weekly", "monday", "hourly"
        trigger_kwargs = {}
        if schedule == "daily":
            trigger_kwargs = {"hour": 8, "minute": 0}
        elif schedule in ("weekly", "monday"):
            trigger_kwargs = {"day_of_week": "mon", "hour": 8, "minute": 0}
        elif schedule == "hourly":
            trigger_kwargs = {"minute": 0}
        elif schedule == "friday":
            trigger_kwargs = {"day_of_week": "fri", "hour": 8, "minute": 0}
        else:
            logger.warning(f"[PRISM Reports] Unknown schedule '{schedule}' for template {template_id}")
            return

        self._scheduler.add_job(
            self._run_scheduled_report,
            trigger="cron",
            id=f"report_{template_id}",
            kwargs={"template_id": template_id},
            **trigger_kwargs,
        )
        logger.info(f"[PRISM Reports] Scheduled '{template['name']}' → {schedule}")

    async def _run_scheduled_report(self, template_id: str):
        """Called automatically by scheduler."""
        logger.info(f"[PRISM Reports] Running scheduled report: {template_id}")
        result = await self.generate_report(template_id, send_email=True)
        if result["success"]:
            logger.info(f"[PRISM Reports] Scheduled report done: {template_id}")
        else:
            logger.error(f"[PRISM Reports] Scheduled report failed: {result.get('error')}")

    # ── Template Management ───────────────────────────────────────────────────

    def register_template(
        self,
        template_id: str = None,
        name: str = "",
        description: str = "",
        connection_id: str = "",
        sql_query: str = "",
        schedule: Optional[str] = None,
        recipients: Optional[List[str]] = None,
        format: str = "excel",
    ) -> Dict[str, Any]:

        if not sql_query.strip().lower().startswith("select"):
            raise ValueError("Only SELECT queries are allowed for reports.")

        template_id = template_id or str(uuid.uuid4())
        template = {
            "id": template_id,
            "name": name,
            "description": description,
            "connection_id": connection_id,
            "sql_query": sql_query.strip(),
            "schedule": schedule,
            "recipients": recipients or [],
            "format": format,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "last_run": None,
            "last_status": None,
            "last_error": None,
            "last_file": None,
            "run_count": 0,
        }
        self._report_templates[template_id] = template

        if schedule and self._scheduler:
            self._schedule_template(template)

        logger.info(f"[PRISM Reports] Registered template '{name}' ({template_id})")
        return template

    def get_template(self, template_id: str) -> Optional[Dict[str, Any]]:
        return self._report_templates.get(template_id)

    def list_templates(self) -> List[Dict[str, Any]]:
        return list(self._report_templates.values())

    def delete_template(self, template_id: str) -> bool:
        if template_id in self._report_templates:
            # Remove scheduler job
            if self._scheduler:
                try:
                    self._scheduler.remove_job(f"report_{template_id}")
                except Exception:
                    pass
            del self._report_templates[template_id]
            return True
        return False

    # ── Report Generation ─────────────────────────────────────────────────────

    async def generate_report(
        self,
        template_id: str,
        format: ExportFormat = None,
        send_email: bool = False,
    ) -> Dict[str, Any]:
        """Generate a report from a registered template."""

        if template_id not in self._report_templates:
            return {"success": False, "error": f"Template not found: {template_id}"}

        template = self._report_templates[template_id]

        # Determine export format
        fmt_str = template.get("format", "excel")
        if format is None:
            format = ExportFormat.EXCEL if fmt_str == "excel" else ExportFormat.PDF

        try:
            success, columns, results, error = await db_manager.execute_query(
                connection_id=template["connection_id"],
                sql=template["sql_query"],
            )

            if not success:
                template["last_status"] = "failed"
                template["last_error"] = error
                return {"success": False, "error": error, "template_id": template_id}

            query_response = QueryResponse(
                query_id=f"report_{template_id}_{int(datetime.now(timezone.utc).timestamp())}",
                natural_language=f"Report: {template['name']}",
                generated_sql=template["sql_query"],
                explanation=f"Auto-generated: {template['description']}",
                success=True,
                execution_time_ms=0,
                row_count=len(results),
                columns=columns,
                results=results,
                timestamp=datetime.now(timezone.utc),
            )

            export_request = ExportRequest(
                query_id=query_response.query_id,
                format=format,
                filename=f"report_{template['name'].replace(' ','_')}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}",
                title=template["name"],
                description=template["description"],
            )

            filepath = await export_service.export(export_request, query_response)

            template["last_run"] = datetime.now(timezone.utc).isoformat()
            template["last_status"] = "success"
            template["last_file"] = filepath
            template["last_error"] = None
            template["run_count"] = template.get("run_count", 0) + 1

            # Email delivery
            email_sent = False
            if send_email and template["recipients"]:
                subject = f"📊 PRISM Report: {template['name']} — {datetime.now(timezone.utc).strftime('%d %b %Y')}"
                body = _report_email_html(template, len(results), filepath)
                email_sent = _send_report_email(template["recipients"], subject, body, filepath)

            return {
                "success": True,
                "filepath": filepath,
                "template_id": template_id,
                "row_count": len(results),
                "columns": columns,
                "email_sent": email_sent,
            }

        except Exception as e:
            logger.error(f"[PRISM Reports] generate_report error: {e}")
            template["last_status"] = "failed"
            template["last_error"] = str(e)
            return {"success": False, "error": str(e), "template_id": template_id}

    # ── Database Summary Report ───────────────────────────────────────────────

    async def generate_summary_report(
        self,
        connection_id: str,
        dialect: DatabaseDialect = DatabaseDialect.POSTGRESQL,
        title: str = "Database Summary Report",
    ) -> Dict[str, Any]:
        from .schema_discovery import schema_discovery
        schema_data = await schema_discovery.discover_full_schema(connection_id)

        summary = {
            "title": title,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "database": {
                "total_tables": schema_data.get("table_count", 0),
                "total_relationships": schema_data.get("relationship_count", 0),
            },
            "tables": [],
        }

        for table in schema_data.get("tables", []):
            table_name = table.get("name", "")
            if dialect == DatabaseDialect.MYSQL:
                sql = f"SELECT COUNT(*) as cnt FROM `{table_name}`"
            else:
                sql = f'SELECT COUNT(*) as cnt FROM "{table_name}"'

            success, _, results, _ = await db_manager.execute_query(
                connection_id=connection_id, sql=sql
            )
            row_count = results[0].get("cnt", 0) if success and results else 0
            summary["tables"].append({
                "name": table_name,
                "columns": len(table.get("columns", [])),
                "primary_keys": table.get("primary_keys", []),
                "row_count": row_count,
            })

        return summary


# Singleton
report_generator = ReportGenerator()